"""Add secretguard tables

Revision ID: 1de5bc4311b8
Revises: c853addae057
Create Date: 2025-08-23 20:45:49.030260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de5bc4311b8'
down_revision: Union[str, None] = 'c853addae057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret_scans',
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secret_scans_tenant_id'), 'secret_scans', ['tenant_id'], unique=False)
    op.create_table('secret_findings',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('secret_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['secret_scans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secret_findings_location'), 'secret_findings', ['location'], unique=False)
    op.create_index(op.f('ix_secret_findings_tenant_id'), 'secret_findings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_secret_findings_tenant_id'), table_name='secret_findings')
    op.drop_index(op.f('ix_secret_findings_location'), table_name='secret_findings')
    op.drop_table('secret_findings')
    op.drop_index(op.f('ix_secret_scans_tenant_id'), table_name='secret_scans')
    op.drop_table('secret_scans')
    # ### end Alembic commands ###
