"""Add cspm tables

Revision ID: 5c9062dbf33f
Revises: f6554cc06fb3
Create Date: 2025-08-19 22:08:37.273916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9062dbf33f'
down_revision: Union[str, None] = 'f6554cc06fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cspm_scans',
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cspm_scans_tenant_id'), 'cspm_scans', ['tenant_id'], unique=False)
    op.create_table('cspm_findings',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='findingstatus'), nullable=False),
    sa.Column('issue_id', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['cspm_scans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cspm_findings_issue_id'), 'cspm_findings', ['issue_id'], unique=False)
    op.create_index(op.f('ix_cspm_findings_resource_id'), 'cspm_findings', ['resource_id'], unique=False)
    op.create_index(op.f('ix_cspm_findings_status'), 'cspm_findings', ['status'], unique=False)
    op.create_index(op.f('ix_cspm_findings_tenant_id'), 'cspm_findings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: The alter_column commands below are removed for SQLite compatibility.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cspm_findings_tenant_id'), table_name='cspm_findings')
    op.drop_index(op.f('ix_cspm_findings_status'), table_name='cspm_findings')
    op.drop_index(op.f('ix_cspm_findings_resource_id'), table_name='cspm_findings')
    op.drop_index(op.f('ix_cspm_findings_issue_id'), table_name='cspm_findings')
    op.drop_table('cspm_findings')
    op.drop_index(op.f('ix_cspm_scans_tenant_id'), table_name='cspm_scans')
    op.drop_table('cspm_scans')
    # ### end Alembic commands ###
