"""Initial schema with tenants and users

Revision ID: b8710d8cef1a
Revises:
Create Date: 2025-08-19 21:48:52.354822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Import RLS helper functions and table list
from app.common.rls import CREATE_ENABLE_RLS_FUNCTION_SQL, CREATE_DISABLE_RLS_FUNCTION_SQL, RLS_ENABLED_TABLES


# revision identifiers, used by Alembic.
revision: str = 'b8710d8cef1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: The RLS logic below is PostgreSQL-specific and is disabled for the SQLite workaround.
    # When migrating to PostgreSQL, uncomment the following lines.

    # op.execute(CREATE_ENABLE_RLS_FUNCTION_SQL)
    # op.execute(CREATE_DISABLE_RLS_FUNCTION_SQL)

    op.create_table('tenants',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)

    # for table in RLS_ENABLED_TABLES:
    #     op.execute(f"SELECT enable_rls('{table}');")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # for table in RLS_ENABLED_TABLES:
    #     op.execute(f"SELECT disable_rls('{table}');")

    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    # ### end Alembic commands ###
