"""Add kspm tables

Revision ID: c853addae057
Revises: ff1bc70f3516
Create Date: 2025-08-22 22:42:24.134847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c853addae057'
down_revision: Union[str, None] = 'ff1bc70f3516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kspm_scans',
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kspm_scans_cluster_id'), 'kspm_scans', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_kspm_scans_tenant_id'), 'kspm_scans', ['tenant_id'], unique=False)
    op.create_table('kspm_findings',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('issue', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['kspm_scans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kspm_findings_issue'), 'kspm_findings', ['issue'], unique=False)
    op.create_index(op.f('ix_kspm_findings_resource_id'), 'kspm_findings', ['resource_id'], unique=False)
    op.create_index(op.f('ix_kspm_findings_tenant_id'), 'kspm_findings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kspm_findings_tenant_id'), table_name='kspm_findings')
    op.drop_index(op.f('ix_kspm_findings_resource_id'), table_name='kspm_findings')
    op.drop_index(op.f('ix_kspm_findings_issue'), table_name='kspm_findings')
    op.drop_table('kspm_findings')
    op.drop_index(op.f('ix_kspm_scans_tenant_id'), table_name='kspm_scans')
    op.drop_index(op.f('ix_kspm_scans_cluster_id'), table_name='kspm_scans')
    op.drop_table('kspm_scans')
    # ### end Alembic commands ###
