"""Add attackpath tables

Revision ID: f302069bb867
Revises: 1de5bc4311b8
Create Date: 2025-08-23 22:51:39.959607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f302069bb867'
down_revision: Union[str, None] = '1de5bc4311b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attackpath_analyses',
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attackpath_analyses_tenant_id'), 'attackpath_analyses', ['tenant_id'], unique=False)
    op.create_table('attackpath_nodes',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['attackpath_analyses.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attackpath_nodes_node_id'), 'attackpath_nodes', ['node_id'], unique=False)
    op.create_index(op.f('ix_attackpath_nodes_tenant_id'), 'attackpath_nodes', ['tenant_id'], unique=False)
    op.create_table('attackpath_edges',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.String(), nullable=False),
    sa.Column('target_node_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['attackpath_analyses.id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['attackpath_nodes.node_id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['attackpath_nodes.node_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attackpath_edges_tenant_id'), 'attackpath_edges', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attackpath_edges_tenant_id'), table_name='attackpath_edges')
    op.drop_table('attackpath_edges')
    op.drop_index(op.f('ix_attackpath_nodes_tenant_id'), table_name='attackpath_nodes')
    op.drop_index(op.f('ix_attackpath_nodes_node_id'), table_name='attackpath_nodes')
    op.drop_table('attackpath_nodes')
    op.drop_index(op.f('ix_attackpath_analyses_tenant_id'), table_name='attackpath_analyses')
    op.drop_table('attackpath_analyses')
    # ### end Alembic commands ###
