"""Add subscriptions table

Revision ID: f6554cc06fb3
Revises: b8710d8cef1a
Create Date: 2025-08-19 21:57:53.335792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6554cc06fb3'
down_revision: Union[str, None] = 'b8710d8cef1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELED', 'INCOMPLETE', 'TRIALING', name='subscriptionstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    # ### end Alembic commands ###
    # NOTE: The following alter_column commands were generated by autogenerate but are
    # not supported by SQLite. They are removed as part of the SQLite workaround.
    # op.alter_column('tenants', 'id',
    #            existing_type=sa.NUMERIC(),
    #            type_=sa.UUID(),
    #            existing_nullable=False)
    # op.alter_column('users', 'id',
    #            existing_type=sa.NUMERIC(),
    #            type_=sa.UUID(),
    #            existing_nullable=False)
    # op.alter_column('users', 'tenant_id',
    #            existing_type=sa.NUMERIC(),
    #            type_=sa.UUID(),
    #            existing_nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
