"""Add ciem tables

Revision ID: ff1bc70f3516
Revises: 5c9062dbf33f
Create Date: 2025-08-22 22:25:02.478911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1bc70f3516'
down_revision: Union[str, None] = '5c9062dbf33f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciem_scans',
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ciem_scans_tenant_id'), 'ciem_scans', ['tenant_id'], unique=False)
    op.create_table('ciem_findings',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('identity_type', sa.String(), nullable=False),
    sa.Column('issue', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['ciem_scans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ciem_findings_identity_id'), 'ciem_findings', ['identity_id'], unique=False)
    op.create_index(op.f('ix_ciem_findings_issue'), 'ciem_findings', ['issue'], unique=False)
    op.create_index(op.f('ix_ciem_findings_tenant_id'), 'ciem_findings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ciem_findings_tenant_id'), table_name='ciem_findings')
    op.drop_index(op.f('ix_ciem_findings_issue'), table_name='ciem_findings')
    op.drop_index(op.f('ix_ciem_findings_identity_id'), table_name='ciem_findings')
    op.drop_table('ciem_findings')
    op.drop_index(op.f('ix_ciem_scans_tenant_id'), table_name='ciem_scans')
    op.drop_table('ciem_scans')
    # ### end Alembic commands ###
